service: tongueTwister

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  # For Customers/Devices located in North America, use us-east-1
  # For Customers/Devices located in Europe and India, use eu-west-1
  # For Customers/Devices located in Far East, use us-west-2 or ap-northeast-1
  region: ap-southeast-1
  memorySize: 128
  timeout: 5
  environment:
    ALEXA_SKILL_ID: amzn1.ask.skill.f143a175-359e-453e-aa75-938f5eb5f3a5

functions:
  tongueTwister:
    handler: index.handler
    name: ${self:service}-${self:provider.stage}
    events:
      - alexaSkill: ${self:provider.environment.ALEXA_SKILL_ID}
